# .github/workflows/ci-cd.yml
name: Publish Python 🐍 distribution 📦 to PyPI

on:
  push:
    # Publish only on tag pushes that look like version tags (e.g., v1.0.0)
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read  # to fetch repo contents
      packages: write
      id-token: write  # needed for pypa/gh-action-pypi-publish

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.5'  # Set your required Python version

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel build

    - name: Build package
      run: python -m build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # PyPI API token stored as a secret in your repo settings
        # Create one here: https://pypi.org/manage/account/#api-tokens
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
